services:
  website:
    build:
      context: ./services/website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # volumes:
    #   - ./services/website/src:/app/src