apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-openbao-client-k8s-auth
  namespace: dummy-openbao-client-k8s-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-openbao-client-k8s-auth
  template:
    metadata:
      labels:
        app: dummy-openbao-client-k8s-auth
    spec:
      serviceAccountName: dummy-openbao-client-k8s-auth-serviceaccount
      containers:
        - name: dummy-openbao-client
          image: dsuprunov/dummy-openbao-client-k8s-auth:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-openbao-client-k8s-auth
  namespace: dummy-openbao-client-k8s-auth
spec:
  selector:
    app: dummy-openbao-client-k8s-auth
  ports:
    - port: 80
      targetPort: 80
  type: NodePort